name: gobank
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  qr_code_scanner:
  flutter_onboarding_screen: ^2.0.2
  provider: ^6.0.2
  shared_preferences: ^2.2.1
  pinput: 1.2.0
  dotted_border: ^2.0.0+2
  slide_to_act: ^2.0.1
  fluttertoast: ^8.0.9
  accordion: ^2.2.3
  fl_chart: ^0.46.0
  charts_flutter: ^0.12.0
  syncfusion_flutter_charts: ^19.1.54
  syncfusion_flutter_gauges:
  dio: ^5.3.3
  flutter_overlay_loader: ^2.0.0
  validatorless: ^1.2.3


 # flutter_localizations:
   # sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Gilroy Black
      fonts:
        - asset: fonts/Gilroy-Black.ttf
    - family: Gilroy Light
      fonts:
        - asset: fonts/Gilroy-Light.ttf
    - family: Gilroy Heavy
      fonts:
        - asset: fonts/Gilroy-Heavy.ttf
    - family: Gilroy Medium
      fonts:
        - asset: fonts/Gilroy-Medium.ttf
    - family: Gilroy Bold
      fonts:
        - asset: fonts/Gilroy-Bold.otf
    - family: Gilroy ExtraBold
      fonts:
        - asset: fonts/Gilroy-ExtraBold.otf
